#! /usr/bin/python

from math import log10
from random import randint
import sys

def radixsort( aList ):
  RADIX = 10
  maxLength = False
  tmp , placement = -1, 1
 
  while not maxLength:
    maxLength = True
    # declare and initialize buckets
    buckets = [list() for _ in range( RADIX )]
 
    # split aList between lists
    for  i in aList:
      tmp = i / placement
      buckets[tmp % RADIX].append( i )
      if maxLength and tmp > 0:
        maxLength = False
 
    # empty lists into aList array
    a = 0
    for b in range( RADIX ):
      buck = buckets[b]
      for i in buck:
        aList[a] = i
        a += 1
 
    # move to next digit
    placement *= RADIX



tamanho = input()
x=[None]*tamanho

for i in range(0,tamanho):		#	recebe os valores de entrada
	 x[i] = input()


minimo = min(x)			#	acha o menor valor do vetor

if minimo < 0:
	minimo = minimo*(-1)

for i in range(0,tamanho):		#	translacao do vetor
	 x[i] = x[i]+minimo

maximo = max(x)

digitos = len(str(maximo))
if digitos <= 5: 
	radixsort(x)	# chama a funcao
else:
	print "Deu ruim! Tamanho: "+str(digitos)

for i in range(0,tamanho):  	#	subtrai o o minimo de todos os valores do vetor
	 x[i] = x[i]-minimo

for i in xrange(0,len(x)):		#	imprime o vetor ordenado 
	print	x[i]


#print "Minimo: "+str(minimo)
